package exceptionHandling;

public class tryCatch {

	//Try catch is used to handle the exception we received while executing respected action,
	//Nested catch can be defined,
	//Throws and Throw
	//Two type of exception available checked and unchecked exception,
	//Checked exception defined at compile time,
	//Unchecked exception found at runtime exception (Array index out of bound, )
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try {
		int i = 10;
		
		int p = 10/0;
		System.out.println(p);
		}
		
		catch (ArithmeticException e){
			
			System.out.println(e.getMessage());
			System.out.println(e.getStackTrace());
		}
		
	}

}
